version: '3.8'

services:
  pdf-converter:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - LOG_LEVEL=info
      - ENVIRONMENT=production
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Exemplo de n8n (descomente se quiser rodar junto)
  # n8n:
  #   image: n8nio/n8n
  #   ports:
  #     - "5678:5678"
  #   environment:
  #     - N8N_BASIC_AUTH_ACTIVE=true
  #     - N8N_BASIC_AUTH_USER=admin
  #     - N8N_BASIC_AUTH_PASSWORD=password
  #   volumes:
  #     - n8n_data:/home/node/.n8n
  #   restart: unless-stopped
  #   depends_on:
  #     pdf-converter:
  #       condition: service_healthy

# volumes:
#   n8n_data:
